### ISSUE TITLE
Мелкие косяки

### ISSUE THREAD

**Issue by aleksei-riaguzov** [upaul23/DataGenerator#3]
**1. Переделать на camelCase**
pro.dagen.person.PersonGenerator#parentnames
pro/dagen/person/PersonGenerator.java:72 String parentname
pro.dagen.person.FIO#parentname

**2. Опечатки**
pro.dagen.person.FIO#fisrtname
pro.dagen.address.AddressGenerator#disctricts
pro.dagen.account.PersoneType

**4. Лишние/не хватающие пробелы**
Тут очень много всего. Хотелось бы иметь единообразие и общий подход во всем. Если в одном классе между полями и фигурными скобками нет пробела, то и в других делать так же.

Пример без пробелов:
```
public class FakeRussianPassport {
    String series;
    String number;
    String issued;
    String issueDate;
    String code;
}
```

Пример с пробелами:
```
public class FakePerson {

    private FIO fio;
    private Gender gender;
    private String birthDate;

}
```

Плюс есть классы, где ни то, ни другое:
```
public class FIO {

    private String fisrtname;
    private String lastname;
    private String parentname;
}
```

И другие места, где просто лишние пробелы. Например, pro/dagen/person/PersonGenerator.java:76:
 ```
   private String getFemaleParentName(){
        String parentname = Randomizer.getRandomElementFromList(parentnames);
        return parentname.replaceAll("вич", "ова");
    }


}
``` 

Неплохо бы пройтись по всем классам и навести красоту. 

**5. А вообще стоит запустить анализатор кода и посмотреть все warnings.** 
Некоторые места, которые он подсвечивает, действительно стоит исправить. Например:

```
        String bikSubstring = String.format(bik.substring(6,9)); //Redundant call to 'format()' 
        String copyAccount = new String(account); // 'new String' is redundant 
```

**Comment by upaul23** [comment]
Исправлено в 1.2.0
